### ISSUE TITLE
Not working on Safari and Firefox.

### ISSUE THREAD

**Issue by perdona** [Juicy/juicy-html#12] opened 2015-10-21 20:54 UTC
Anyone having problems in Safari/Firefox?
No matter where my import is, I get the errors:

![screen shot 2015-10-21 at 18 52 52](https://cloud.githubusercontent.com/assets/7670956/10649852/135ab580-7825-11e5-9883-47f93a3c4a19.png)

**Comment by spirylics** [comment] 2015-11-24 15:36
+1

**Comment by tomalec** [comment] 2015-12-22 19:26
Sorry, that it it's still not resolved. All, I get so far is the lack of support for createContextualFragment in Safari :/

Regarding Firefox, from what I can get on my machine, travis, and soucelabs it works fine. Could you provide more details on FF?

**Comment by tomalec** [comment] 2015-12-23 18:33
@perdona, @spirylics  I have created a [branch for this issue](https://github.com/Juicy/juicy-html/tree/issues/13-createContextualFragment-in-safari) Could you, please, check if my solution works for you?
https://travis-ci.org/Juicy/juicy-html shows it works better than before :)

**Comment by spirylics** [comment] 2016-01-04 20:50
Thanks, it works now with safari / firefox but it's broken on chrome

**Comment by miyconst** [comment] 2016-01-14 15:22
Duplicate of https://github.com/Juicy/juicy-html/issues/13. Fixed. Please check it.

**Closed by miyconst** 2016-01-14 15:22 UTC
